name: API tests

on:
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

# Права для деплоя GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Ruff
        run: pip install ruff

      - name: Ruff check
        run: ruff check .

      - name: Docker Compose up
        working-directory: docker_folder
        run: docker compose up -d --build

      - name: Run tests (host network)
        run: |
          NETWORK=$(docker network ls --filter name=docker_folder_default -q)
          docker run --rm --network $NETWORK my-tests

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Allure CLI
        run: npm i -g allure-commandline --no-fund --no-audit

      - name: Generate Allure report
        run: allure generate allure-results --clean -o _site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4