name: API tests

on:
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linter

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Ruff
        run: pip install ruff

      - name: Ruff check
        run: ruff check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    name: Tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Docker Compose up
        working-directory: docker_folder
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB_AUTH: ${{ secrets.POSTGRES_DB_AUTH }}
          POSTGRES_DB_UNIVERSITY: ${{ secrets.POSTGRES_DB_UNIVERSITY }}
          AUTH_SERVICE_INTERNAL_URL: ${{ secrets.AUTH_SERVICE_INTERNAL_URL }}
          AUTH_SERVICE_API_URL: ${{ secrets.AUTH_SERVICE_API_URL }}
          UNIVERSITY_SERVICE_INTERNAL_URL: ${{ secrets.UNIVERSITY_SERVICE_INTERNAL_URL }}
          UNIVERSITY_SERVICE_API_URL: ${{ secrets.UNIVERSITY_SERVICE_API_URL }}
        run: docker compose up -d --build

      - name: Build test container
        run: docker build -t my-tests .

      - name: Run tests (host network, capture exit code)
        run: |
          set +e
          docker run --rm --network host \
            -v ${{ github.workspace }}/allure-results:/app/allure-results \
            my-tests
          exit_code=$?
          set -e

          if [ "$exit_code" = "0" ]; then
            echo -e "\033[0;32mAll tests passed ✅\033[0m"
          else
            echo -e "\033[0;31mSome tests failed ❌\033[0m"
          fi

      - name: Store allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate report

    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz
          sudo tar -zxvf allure-2.23.1.tgz -C /opt/
          sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure

      - name: Download allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Generate Allure report
        run: allure generate -c allure-results -o allure-reports

      - name: Store generated report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-reports
          retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Report publication

    steps:
      - name: Download generated report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-reports

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-reports

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
